# Generated by Django 5.0 on 2023-12-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0003_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(
                choices=[('game', 'game'), ('irl', 'irl'), ('event', 'event')],
                default='game', max_length=50),
        ),
    ]
