# Generated by Django 5.0 on 2023-12-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0004_alter_news_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='my_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserNewsRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('news',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='news.news')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='readers',
            field=models.ManyToManyField(related_name='news',
                                         through='news.UserNewsRelation',
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
