# Generated by Django 5.0 on 2023-12-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('News', '0005_alter_news_author_usernewsrelation_news_readers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
