# Generated by Django 5.0 on 2023-12-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0007_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='news',
                                    verbose_name='Изображение'),
        ),
    ]
