# Generated by Django 5.0 on 2023-12-11 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0008_alter_news_options_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
