# Generated by Django 5.0 on 2023-12-15 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('news', '0009_news_date_created_news_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-date_created',), 'verbose_name': 'news',
                     'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='usernewsrelation',
            options={'verbose_name': 'User-news Relation',
                     'verbose_name_plural': 'User-news Relation'},
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='news.category'
            ),
        ),
    ]
